<?php
/**
 * Created by PhpStorm.
 * User: pawel
 * Date: 08.01.18
 * Time: 18:36
 */

use Admin\Form\AddClientGroupForm;

?>
<div class="col-lg-4">
    <div id="ibox" class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Zarządzaj grupami</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content" style="min-height: 200px">
            <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#myModalGroups">Dodaj grupę</button>
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover dataTables-groups">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Nazwa</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $i = 1; foreach ($groups as $group): ?>
                        <tr>
                            <td><?= $i ?></td>
                            <td><?= $group->getName(); ?></td>
                        </tr>
                    <?php $i++; endforeach; ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>#</th>
                        <th>Nazwa</th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal inmodal" id="myModalGroups" tabindex="-1" role="dialog" aria-hidden="true">
    <?php $form->prepare(); ?>
    <?= $this->form()->openTag($form); ?>
    <div class="modal-dialog">
        <div class="modal-content animated fadeInDown">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Zmień grupę użytkownika</h4>
            </div>
            <div class="modal-body">
                <?= $this->formLabel($form->get(AddClientGroupForm::NAME)); ?>
                <?= $this->formInput($form->get(AddClientGroupForm::NAME)); ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Zamknij</button>
                <?= $this->formSubmit($form->get(AddClientGroupForm::SUBMIT)); ?>
            </div>
        </div>
    </div>
    <?= $this->form()->closeTag(); ?>
</div>
<script>
    $(document).ready(function(){
        $('.dataTables-groups').DataTable({
            pageLength: 10,
            responsive: true,
            dom: 'lTfgitp',
            language: {
                "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Polish.json"
            }
        });
        // $('.select2').select2({
        //     placeholder: "Wybierz grupę"
        // });
    });
</script>
