<?php
/**
 * Created by PhpStorm.
 * User: pawel
 * Date: 08.01.18
 * Time: 10:29
 */
use Admin\Form\AddClientAppForm;
?>
<?= $this->partial('partial/messages', ['messages' => $messages]); ?>
<div class="col-lg-12">
    <div id="ibox" class="ibox float-e-margins">
        <div class="ibox-title">
            <h5><?= $title ?></h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content" style="min-height: 200px">
            <div class="form-group">
                <?php $form->prepare(); ?>
                <?= $this->form()->openTag($form); ?>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <?= $this->formLabel($form->get(AddClientAppForm::CLIENT_NAME)) ?>
                            <?= $this->formInput($form->get(AddClientAppForm::CLIENT_NAME)) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($form->get(AddClientAppForm::CLIENT_IDENTIFIER)) ?>
                            <?= $this->formInput($form->get(AddClientAppForm::CLIENT_IDENTIFIER)) ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($form->get(AddClientAppForm::CLIENT_SECRET)) ?>
                            <?= $this->formInput($form->get(AddClientAppForm::CLIENT_SECRET)) ?>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <?= $this->formLabel($form->get(AddClientAppForm::USERS)); ?>
                            <?= $this->formSelect($form->get(AddClientAppForm::USERS)); ?>
                        </div>
                        <div class="form-group">
                            <?= $this->formLabel($form->get(AddClientAppForm::REDIRECT_URI)) ?>
                            <?= $this->formInput($form->get(AddClientAppForm::REDIRECT_URI)) ?>
                        </div>
                        <div class="form-group">
                            <div class="radio i-checks">
                                <?= $this->formLabel($form->get(AddClientAppForm::CLIENT_TYPE)) ?>
                                <?= $this->formRadio($form->get(AddClientAppForm::CLIENT_TYPE)) ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <?php if (!$hide): ?>
                            <?= $this->formSubmit($form->get(AddClientAppForm::SUBMIT)); ?>
                        <?php else: ?>
                            <a class="btn btn-primary pull-right" href="<?= $this->url('apps', ['action' => 'edit', 'id' => $id]) ?>">Edytuj</a>
                        <?php endif; ?>
                        <?= $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
        $('.chosen-select').chosen({width: "100%"});
    });
</script>