<?php
/**
 * Created by PhpStorm.
 * User: pawel
 * Date: 31.01.18
 * Time: 00:06
 */

namespace Api\Controller\v2;


use RestApi\Controller\ApiController;

class UserController extends ApiController
{
    public function get($id)
    {
        var_dump('aaaaaa');die;
        return parent::get($id); // TODO: Change the autogenerated stub
    }

}