<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.ico'])
        ->prependStylesheet($this->basePath() . '/css/paml-auth.css')
        ->prependStylesheet($this->basePath() . '/css/style-auth.css')
        ->prependStylesheet($this->basePath() . '/css/animate.css')
        ->prependStylesheet($this->basePath() . '/css/textSpinners/spinners.css')
        ->prependStylesheet($this->basePath() . '/css/iCheck/custom.css')
        ->prependStylesheet($this->basePath() . '/css/toastr/toastr.min.css')
        ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath() . '/js/toastr/toastr.min.js')
        ->prependFile($this->basePath() . '/js/pwstrength/zxcvbn.js')
        ->prependFile($this->basePath() . '/js/pwstrength/pwstrength-bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/iCheck/icheck.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.js')
        ->prependFile($this->basePath() . '/js/jquery-3.1.1.min.js')
    ?>
</head>
<body class="gray-bg">
<div class="animated fadeInDown text-center">
    <img style="margin-top: 5%; width: 20%" src="<?= $this->basePath('img/logo.png') ?>">
</div>
<div class="middle-box text-center loginscreen animated fadeInDown">
    <div>
        <?= $this->content ?>
    </div>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
