<?php
/**
 * Created by PhpStorm.
 * User: pawel
 * Date: 08.01.18
 * Time: 10:38
 */

echo $this->partial('partial/client-form', ['messages' => $messages, 'form' => $form, 'hide' => true, 'id' => $id, 'title' => $title]);
echo $this->partial('partial/user-list', ['users' => $users, 'form' => $clientUserGroupForm, 'title' => $title, 'id' => $id]);
echo $this->partial('partial/client-groups', ['form' => $addClientGroupForm, 'groups' => $groups]);

