<?php
/**
 * Created by PhpStorm.
 * User: pawel
 * Date: 08.01.18
 * Time: 11:55
 */

use Admin\Form\ChangeClientUserGroupForm;

?>
<div class="col-lg-8">
    <div id="ibox" class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Zarządzaj użytkownikami</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content" style="min-height: 200px">
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover dataTables-example display nowrap" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Nazwa</th>
                        <th>Email</th>
                        <th>Grupa</th>
                        <th>Akcja</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    /**
                     * @var \Auth\Entity\User $user
                     */
                    ?>
                    <?php $i = 1; foreach ($users as $user): ?>
                        <tr>
                            <td><?= $i ?></td>
                            <td><?= $user->getLogin(); ?></td>
                            <td><?= $user->getEmail(); ?></td>
                            <td><?= $user->getGroupsWithClient($id)[0]->getGroup()->getName(); ?></td>
                            <td>
                                <button id="<?= $user->getId(); ?>" type="button" class="btn btn-primary btn-xs js-add-user" data-toggle="modal" data-target="#myModal">Zmień grupę</button>
                            </td>
                        </tr>
                    <?php $i++; endforeach; ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <th>#</th>
                        <th>Nazwa</th>
                        <th>Email</th>
                        <th>Grupa</th>
                        <th>Akcja</th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal inmodal" id="myModal" role="dialog" aria-hidden="true">
    <?php $form->prepare(); ?>
    <?= $this->form()->openTag($form); ?>
    <div class="modal-dialog">
        <div class="modal-content animated fadeInDown">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Zmień grupę użytkownika</h4>
            </div>
            <div class="modal-body">
                <?= $this->formInput($form->get(ChangeClientUserGroupForm::USER)); ?>
                <?= $this->formLabel($form->get(ChangeClientUserGroupForm::GROUP)); ?>
                <?= $this->formSelect($form->get(ChangeClientUserGroupForm::GROUP)); ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Zamknij</button>
                <?= $this->formSubmit($form->get(ChangeClientUserGroupForm::SUBMIT)); ?>
                <script>
                    $(document).ready(function () {
                        $('.select2').select2();
                    });
                </script>
            </div>
        </div>
    </div>
    <?= $this->form()->closeTag(); ?>
</div>
<script>
    $(document).ready(function(){
        $('.js-add-user').on('click', function () {
            $('.js-user').val($(this).attr('id'));
        });
        $.extend($.fn.dataTable.defaults, {
            responsive: true
        });
        $('.dataTables-example').DataTable({
            pageLength: 10,
            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                {extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'Użytkownicy'},
                {extend: 'pdf', title: 'Użytkownicy'},
                {extend: 'print',
                    customize: function (win){
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');
                        $(win.document.body).find('table')
                            .addClass('compact')
                            .css('font-size', 'inherit');
                    }
                }
            ],
            language: {
                "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Polish.json"
            }
        });
        $('.select2').select2({
            placeholder: "Wybierz grupę"
        });
    });
</script>
