<?php
/**
 * Created by PhpStorm.
 * User: pawel
 * Date: 16.11.17
 * Time: 09:04
 */

use Auth\Form\UserLoginForm;


$form->prepare();
?>
<?= $this->headTitle(Application\Module::APP_NAME . ' | Logowanie')->setSeparator(' - ')->setAutoEscape(false) ?>
<?= $this->partial('partial/messages', ['messages' => $messages]); ?>
<?= $this->form()->openTag($form); ?>
    <div class="form-group">
        <?= $this->formLabel($form->get(UserLoginForm::LOGIN)); ?>
        <?= $this->formInput($form->get(UserLoginForm::LOGIN)); ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($form->get(UserLoginForm::PASSWORD)); ?>
        <?= $this->formInput($form->get(UserLoginForm::PASSWORD)); ?>
    </div>
    <?= $this->formInput($form->get(UserLoginForm::REDIRECT_URL)); ?>
    <?= $this->formInput($form->get(UserLoginForm::CSRF)); ?>
    <div class="form-group">
        <div class="checkbox i-checks">
            <?= $this->formInput($form->get(UserLoginForm::REMEMBER_ME)); ?>
            <?= $this->formLabel($form->get(UserLoginForm::REMEMBER_ME)); ?>
        </div>
    </div>
    <?= $this->formSubmit($form->get(UserLoginForm::SUBMIT)); ?>
<?= $this->form()->closeTag(); ?>
<a href="<?= $this->url('auth', ['action' => 'makeNewPassword']) ?>"><small>Zapomniałeś hasła?</small></a>
<p class="text-muted text-center"><small>Nie masz jeszcze konta?</small></p>
<a class="btn btn-sm btn-white btn-block" href="<?= $this->url('auth', ['action' => 'register']) ?>">Utwórz konto</a>
<script>
    $(document).ready(function(){
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });
</script>

