<?php
/**
 * Created by PhpStorm.
 * User: pawel
 * Date: 18.11.17
 * Time: 15:57
 */

use Auth\Form\UserRegisterForm;

$form->prepare();
?>
<?= $this->headTitle(Application\Module::APP_NAME . ' | Rejestracja')->setSeparator(' - ')->setAutoEscape(false) ?>
<?= $this->partial('partial/messages', ['messages' => $messages]); ?>
<?= $this->form()->openTag($form); ?>
<div class="form-group">
    <?= $this->formRow($form->get(UserRegisterForm::LOGIN)); ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get(UserRegisterForm::EMAIL)); ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get(UserRegisterForm::PASSWORD)); ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get(UserRegisterForm::REPASSWORD)); ?>
</div>
<div class="form-group">
    <div class="pwstrength_viewport_progress"></div>
</div>
<?= $this->formRow($form->get(UserRegisterForm::CSRF)); ?>
<?= $this->formSubmit($form->get(UserRegisterForm::SUBMIT)); ?>
<?= $this->form()->closeTag(); ?>
<p class="text-muted text-center"><small>Masz już konto?</small></p>
<a class="btn btn-sm btn-white btn-block" href="<?= $this->url('auth', ['action' => 'login']) ?>">Zaloguj</a>

<script>
    var options = {};
    options.ui = {
        container: "#register",
        showVerdictsInsideProgressBar: true,
        viewports: {
            progress: ".pwstrength_viewport_progress"
        }
    };
    options.common = {
        zxcvbn: true,
        userInputs: ['#login', '#email']
    };
    $('#password').pwstrength(options);
</script>
